kind: Service
apiVersion: v1
metadata:
  name: kubernities-app
spec:
  selector:
    app: kubernities-app
  type: NodePort         # LoadBalancer se NodePort me change kiya
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080    # NodePort 30000-32767 ke beech
