kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: kubernities-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 8080
  selector:
   app: kubernities-app
  type: LoadBalancer