kind: Service
apiVersion: v1
metadata:
  name: kubernities-app
spec:
  selector:
    app: kubernities-app
  type: LoadBalancer   # NodePort -> LoadBalancer
  ports:
    - name: http
      port: 8080        # External access port
      targetPort: 8080  # Pod port
